<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="ARPITA" failures="1" tests="5" name="Personal Loan" time="0.319" errors="0" timestamp="2024-01-13T15:21:12 IST">
  <testcase classname="test.day2" name="ploan" time="0.04"/>
  <testcase classname="test.day1" name="Demo" time="0.072">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.day1.Demo(day1.java:18)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase classname="test.day4" name="LoginAPIHomeLoan" time="0.007"/>
  <testcase classname="test.day4" name="MobileLoginHomeLoan" time="0.002"/>
  <testcase classname="test.day4" name="WebLoginHomeLoan" time="0.002"/>
  <testcase classname="test.day1" name="SecondTest" time="0.0">
    <ignored/>
  </testcase> <!-- SecondTest -->
</testsuite> <!-- Personal Loan -->
